- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
In updating the wrapper layout in static this needs to be accounted for
in this application. Add a grid-row div so the related and main columns
float.
This is the matching pull request to go with this one on static: alphagov/static#530
> Update to work with slimmer wrapper layout

- app/views/calendar/_calendar_by_year.html.erb
For example, copying a table into excel or google drive, if the value of the date cell
is '2 April' then it will be detected as a date, but the year will default to the current.
For past/future years this results in the wrong year. If we provide a visually and AT
hidden year for this case then the date will be parsed entirely correctly.
This is doubly-hidden content, but as it's entirely progrmatic its unlikely to go stale,
as static copy may.
**Note**: I could not get this to work without the `&nbsp;`. With a regular space it would copy as `D M Y`, but be treated by google drive as `D MY`.
Thoughts?
> Adding a (hidden) date allows spreadsheet programs to parse dates when copy/pasting

- Gemfile
- Gemfile.lock
- app/views/calendar/_calendar_metadata.html.erb
This picks up using meta tags for page metadata (instead of setting
GA custom dimensions).
This upgrade requires removing the report-a-problem div, meaning that
the report-a-problem form is automatically appended to the wrapper
by slimmer.
/cc @fofr
> Bump slimmer to 8.1.0

- app/assets/stylesheets/application.css.scss
Bunting was not showing correctly on a bank holiday. It started from the left side of the grid. 
This PR is in combination with changes to static, which remove the bunting styles that were over there.
* Hang bunting across full page width by positioning absolutely
* Tweak the top margins for content and related links
* Use the same media queries for modifying margins as used for hiding the bunting
There's a white space commit, so I suggest reviewing with `?w=1`
https://www.pivotaltracker.com/story/show/93891364
cc @futurefabric @edds @wryobservations
> Re-hang the bunting so it looks alright

- config/locales/en.yml
Having link text the same as the title makes reading the link out really
repetitive for a screen reader user as it will read the same text twice.
Remove the repeated text as you get all the content you need from the
link text.
> Remove link title

- Gemfile
- Gemfile.lock
- app/models/services.rb
- app/presenters/calendar_content_item.rb
- app/services/calendar_publisher.rb
- config/application.rb
- lib/data/bank-holidays.json
- lib/data/when-do-the-clocks-change.json
- lib/registerable_calendar.rb
- lib/tasks/panopticon.rake
- lib/tasks/publishing_api.rake
- test/support/content_schema_helpers.rb
- test/test_helper.rb
- test/unit/panopticon_registration_test.rb
- test/unit/presenters/calendar_content_item_test.rb
- test/unit/services/calendar_publisher_test.rb
This commit adds a `content_id` (generated in the console with `SecureRandom.uuid`) to the two calendars.
By updating `gds-api-adapters` and exposing a `content_id` method on `RegisterableCalendar`, this attribute is automatically sent to panopticon. Also sends the calendars to the content-store.
https://trello.com/c/A94Y5Ect
> Add `content_id` to calendars and send to panopticon, content-store

- jenkins.sh
Without this, the CI build on master will fail.
> Setup CI before running tests

- app/models/calendar.rb
- app/presenters/calendar_content_item.rb
- test/fixtures/data/bank-holidays.json
- test/unit/presenters/calendar_content_item_test.rb
PR #93 sets up the infrastructure for sending the `content_id` to the content-store very nicely, but completely forgets to actually _send the the content_id to the content-store_.
:flushed: 
Trello: https://trello.com/c/A94Y5Ect
> Send content_id to publishing-api

- config/secrets.yml
This commit changes Calendars to use the secret key base env var that is
set in Puppet.
> Use key base from env var

- app/assets/stylesheets/application.css.scss
- config/application.rb
The asset prefix was removed by mistake in the upgrade to Rails 4
https://github.com/alphagov/calendars/commit/abc5a1b2c6368c7230c8e4e593c444e7e0231d3f
> Fix asset prefix and image paths

- Gemfile
- Gemfile.lock
Everyone has `nodejs` and it will be detected by `ExecJS` which is
tasked with finding a usable JS runtime. Plus `libv8` is a beast of a
dependency to build and therefore contributes to global warming.
> Drop the rubyracer dependency

- Gemfile
- Gemfile.lock
- app/presenters/calendar_content_item.rb
- app/services/calendar_publisher.rb
- lib/services.rb
- test/unit/services/calendar_publisher_test.rb
All apps should now use v2 of the publishing api to write content to the content-store. This change converts calendars to use v2 of the api. The differences are:
- put content_item is replaced by two methods - put_content, and publish
- the content_id is used as the key, rather than the base path
- the base path is included in the payload
> Use V2 of publishing-api to write calendars to the content store

- app/presenters/calendar_content_item.rb
- test/test_helper.rb
- test/unit/presenters/calendar_content_item_test.rb
We should test against the new v2 schemas. Doing this uncovered that `update_type` and `content_id` were being sent, while they shouldn't.
https://trello.com/c/catWOsWC
> Use V2 schema testing

- app/presenters/calendar_content_item.rb
- jenkins-schema.sh
This fixes the payload sent to the publishing-api and adds a script that will be used to test this application from PRs against https://github.com/alphagov/govuk-content-schemas.
> Fix schema testing

- app/controllers/application_controller.rb
- test/functional/calendar_controller_test.rb
This adds CORS headers for JSON requests so the data can be used directly by javascript applications. This was requested in https://github.com/alphagov/calendars/issues/113.
This pattern was taken from the e-petitions application (https://github.com/alphagov/e-petitions/pull/382).
To be reviewed by @daibach or @alexmuller.
> Add CORS headers for JSON requests

- README.md
- app/presenters/search_payload_presenter.rb
- app/services/search_indexer.rb
- lib/services.rb
- lib/tasks/rummager.rake
- test/unit/services/search_indexer_test.rb
Previously, panopticon would send artifacts to Rummager. That flow is now being
deprecated in favour of a simpler approach which is to send documents directly
to rummager.
This commit adds a class that allows us to add calendars to the search index
directly. It also adds a rake task `rummager:index_all` which goes through all
calendars and indexes them in the search index.
Before, the search results in `search-admin` looked like this:
After the change, it looks like this:
The payload now includes the following extra attributes:
- publishing_app
- rendering_app
- content_id
Trello ticket: https://trello.com/c/gsHnT5WF/161-epic-send-things-to-rummager-directly-instead-of-via-panopticon
> Rake task to add calendars to the search index

- Gemfile
- Gemfile.lock
- config/initializers/gds_api_adapters.rb
Update to the latest version, particularly as we've updated the Panopticon adapter to stop handling search-related attributes (see https://github.com/alphagov/gds-api-adapters/pull/592).
> Update gds-api-adapters to 36.4.0

- app/presenters/calendar_content_item.rb
- lib/registerable_calendar.rb
- test/unit/panopticon_registration_test.rb
- test/unit/presenters/calendar_content_item_test.rb
- test/unit/services/calendar_publisher_test.rb
This PR makes this application register its routes via the publishing-api instead of content-store.
It's part of the mainstream preparatory work to remove routing from panopticon.
https://trello.com/c/6eOYmUnL/1-register-routes-via-the-publishing-api-for-publisher-formats
> Register routes via publishing-api instead of panopticon

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/helpers/_govuk-component-helpers.scss
- app/controllers/application_controller.rb
- app/controllers/calendar_controller.rb
- app/models/calendar/division.rb
- test/integration/icalendar_test.rb
Finding Things has been working on migrating related links, part of that work was to replace the breadcrumbs on a number of different frontend applications like:
- calendars
- calculators
- business-support-finder
- frontend
- licence-finder
- smart-answers
That work has already been done, this commit aims to clean up things we
have missed during the migration.
This includes
- upgrading Slimmer to 10.0.0
- deletion of govuk-component-helpers.scss
- rename [Slimmer::SharedTemplates to Slimmer::GovukComponents](https://github.com/alphagov/slimmer/pull/173)
- [remove I18n to build the ics calendar](https://github.com/alphagov/calendars/pull/127/commits/241ce1c83d55d6ee24dc5d91a5e46dfd9752b389)
Trello: https://trello.com/c/5Utjs9qw/300-related-links-cleanup
> Upgrade Slimmer and related code

- app/assets/stylesheets/application.scss
- app/models/calendar.rb
- app/views/calendar/bank_holidays.html.erb
- test/integration/bank_holidays_test.rb
For the past few years @rjw1 and I have had a little Christmas tradition of devopsing a change in production to use the tinsel bunting on the bank holidays page over Christmas and New Year.
As part of our valiant quest to automate ourselves out of a job, it turns out that these days computers can even do that for us.
Progress, hey?
> Use tinsel automatically at Christmas and New Year

- lib/data/bank-holidays.json
- lib/data/when-do-the-clocks-change.json
Add the generated JSON data for 2018 bank holidays, following the instructions in the README.
See https://github.com/alphagov/calendars/issues/131
> Add bank holidays for 2018

- lib/registerable_calendar.rb
This class used to be used by both panopticon and rummager. Now that panopticon is removed as a dependency (#135) these methods aren't necessary anymore.
https://trello.com/c/7u8M6zrg
> Remove more things related to panopticon

- Gemfile
- README.md
- startup_heroku.sh
To get a working preview of changes before merging into master, we can deploy the branch to Heroku using this script. It is a modified version of the same script as used in
https://github.com/alphagov/smart-answers/blob/master/startup_heroku.sh
Readme has instructions as taken from
https://github.com/alphagov/smart-answers/blob/master/doc/factcheck.md
Heroku only supports reading the ruby version from the Gemfile. It otherwise defaults to an older version of ruby, that is incompatible with some of the gems being used.
> Add heroku preview deployment script

- Jenkinsfile
The old ci environment is being turned off, so we need to
start building calendars on the new Jenkins version 2
environment.
The new Jenkinsfile builds the code in branches, and runs
the tests against them in the same manner as the
previous jenkins.sh script.
> Add a Jenkinsfile for calendars

- app/presenters/search_payload_presenter.rb
- test/unit/services/search_indexer_test.rb
This change will register the document type in Rummager, so that calendar documents can be found by type.
This is useful for [finding mainstream content](https://trello.com/c/5wrs1iHn/432-load-mainstream-links-from-search-for-the-prototype).
https://trello.com/c/bRXYo6XY/433-update-mainstream-publishing-apps
> Register document type with Rummager

- Rakefile
- app/controllers/calendar_controller.rb
- lib/tasks/lint.rake
- test/integration/icalendar_test.rb
We're getting quite a few requests for paths like /bank-holidays/england-and-wales-2012.ics on Production. These have an invalid division which causes a KeyError.  These have tripped our Fastly 5xx alerts for GOV.UK a few times today, but they're not real pages (at least not any more).
Example: https://errbit.publishing.service.gov.uk/apps/536119100da1151271001052/problems/58aebe536578632b11500200
We should handle these requests with a 404 instead.
I've also added the linter to the default rake task.
> Improve handling of invalid divisions

- Gemfile.lock
This puts a RUBY_VERSION and updates BUNDLED_WITH to the correct version
as per our puppet infrastructure.  Having these left out means useful
scripts in the development VM won't run on this repo because of
uncommitted local changes.
> Re-bundle with new ruby and bundler

- lib/data/when-do-the-clocks-change.json
[Trello card](https://trello.com/c/WOPjWoSa)
Removed 2016 because it's in the past and corrected 28/10/2017 to 28/10/2018.
Supersedes #144
> Remove 2016 clock changes and correcting 2018

- Gemfile
- Gemfile.lock
- app/presenters/calendar_content_item.rb
- app/services/calendar_publisher.rb
- test/unit/services/calendar_publisher_test.rb
Sending it on publish has been deprecated in favour of including it when sending a put content.
[Trello Card](https://trello.com/c/LnJlkb9e/987-5-deprecate-the-usage-of-updatetype-in-publish-for-publishing-api-and-update-usage-across-govuk)
> Send update type with put content

- Jenkinsfile
Hey :wave: !
This PR will enable a set of [end-to-end tests](https://github.com/alphagov/publishing-e2e-tests) for Publisher to run every time a commit is made to this repo. Calendar is a dependency of Publisher so we wanted to ensure there was coverage here too. :boom:
You can read through the scenarios at a [high level](https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1AUYU4n4GN_XGdqUJdONN2pbQnVEC5o8s--59IipeFjY/edit?usp=sharing), and the capybara [here](https://github.com/alphagov/publishing-e2e-tests/tree/master/spec/publisher).
Look at the merge box below and you'll see a new check performed against this PR.
Enabling these tests will give increased confidence when making changes to this repo that the change doesn't break the publisher in an end-to-end environment. …
> Enable running of end-to-end tests related to publisher

- app/controllers/calendar_controller.rb
For: https://trello.com/c/hpS5pFQe/237-investigate-new-navigation-impact-on-surveys
We stripped organisation info from the content item presented to the
view because it would result in the `govuk:analytics:organisations` meta
tag being set and this would be sent to Google Analytics (GA) as a custom
dimension.  We did this because the tag was mostly used by whitehall and
departmental users wouldn't expect to see mainstream content appearing
in their GA reports for their department.
During migration the mainstream formats ported to government-frontend
started sending this info to GA and it didn't cause any problems.  This
means we're happy to stop stripping this data and have all content items
that have organisation info send it to GA.
> Stop stripping organisation info from content item

- Gemfile.lock
This includes a fix that repairs the styles for the feedback form (https://github.com/alphagov/govuk_publishing_components/pull/170).
https://trello.com/c/8TC3AEms
> Bump govuk_publishing_components

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/print.scss
- app/views/layouts/application.html.erb
- config/routes.rb
PR https://github.com/alphagov/calendars/pull/207 temporarily added the feedback component to facilitate testing today. The test seems to have gone fine. This rolls it back so we can launch next week.
https://trello.com/c/eKtXGtBD
> Use the report a problem feedback feature

- app/presenters/calendar_content_item.rb
- app/services/calendar_publisher.rb
- test/unit/services/calendar_publisher_test.rb
GDS is the primary publishing organisation for calendars, because there is no publishing app for them. They are just 2 json files on github.
We are going to set a primary organisation for all content items so that we can group and report on content better.
2 down, 534371 to go....
Trello:
- https://trello.com/c/BNMbxdAO/365-placeholder-set-primary-org-for-calendar
- https://trello.com/c/DFvcvGGX/366-republish-calendar-documents
> Set primary publishing organisation

- app/controllers/application_controller.rb
- test/test_helper.rb
This app isn't consuming any Static-based components anymore, so we don't need to include this and the test helper.
> Remove Slimmer::GovukComponents

- lib/data/when-do-the-clocks-change.json
This is also the meta description in Google, and wasn't updated when the clocks JSON was updated last.
> Update the description for the clocks change page

- config/locales/cy.yml
- config/locales/en.yml
- lib/data/bank-holidays.json
The early May bank holiday 2020 is moving from 04 May to 08 May to mark
the 75th anniversary of VE Day for England, Wales and Northern Ireland. Scotland is staying as it was.
Add an entry to the locale files under `bank_holidays.early_may_ve`.
We have no translation for Welsh yet so I've left it as "VE day".
I've chosen to add a new bank holiday to the locales rather than
include `notes` into the existing May bank holiday. This is because we
explicitly want "VE day" to be capitalised and `notes` are
[dowcased](https://github.com/alphagov/calendars/blob/6d51141ea5a50582305d7dc7f6dc1f0b0a85287a/app/views/components/_calendar.html.erb#L18).
Although we could argue that `notes` fields should be represented
verbatim, I discussed the various options with the content team and decided to
leave …
> Update early May bank holiday 2020 to include VE day

- lib/data/bank-holidays.json
This holiday was changed for England, Wales and Northern Ireland in the
following PR: https://github.com/alphagov/calendars/pull/602
This commit also changes the holiday date for Scotland as requested
here: https://govuk.zendesk.com/agent/tickets/3728504
> Change early May 2020 bank holiday for Scotland

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/objects/_bunting.scss
This PR:
- govuk_publishing_components to 18.0.0
- enables compatibility with `govuk-template` using the following SCSS flag `$govuk-compatibility-govuktemplate: true;`
- updates mixins
>  Update govuk_publishing_components to 18.0.0

- app/controllers/application_controller.rb
- test/functional/calendar_controller_test.rb
Trello: https://trello.com/c/gKND6vZM/169-unauthenticated-user-accessing-a-calendars-page-with-step-by-step-token-is-directed-to-sign-on
Follows on from: [RFC 113: Expanding draft access for unauthenticated users to allow multi-page fact checks](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-113-expanding-draft-access-for-unauthenticated-users.md)
At the moment calendars is throwing a 500 when it receives
an error code it doesn't recognise from content-store. That means
that users are shown a "Problem has occurred" page.
We need to handle this error properly so that in the case of a
403, the user will be properly routed to signon and asked to login
if there is any form of access limiting on the content item (e.g.
hosted on draft stack, access limited to organisation)
> Rescue 403 errors

- Gemfile
- Gemfile.lock
Bumps govuk_publishing_components to version 21.9.0. This includes a change which adds a related link to the Brexit landing page on pages tagged to /brexit, /world/brexit, or any child taxon of /brexit.
https://govuk-calendars-pr-709.herokuapp.com/bank-holidays
> Update govuk_publishing_components to 21.9.0

- .rubocop.yml
- .scss-lint.yml
- Gemfile
- Gemfile.lock
- lib/tasks/lint.rake
- The GOV.UK Lint gem is deprecated in favour of using Rubocop directly
with a set of shared configs.
- See https://github.com/alphagov/govuk-rfcs/pull/ 100 for more context.
https://trello.com/c/CdBFg6yw/1521-replace-govuk-lint-with-rubocop-govuk
> Use `rubocop-govuk` and `scss_lint-govuk` instead of `govuk-lint`

- app/assets/stylesheets/application.scss
GOV.UK Frontend (Design System) version 3 has [better colour contrast](https://designnotes.blog.gov.uk/2019/07/29/weve-updated-the-gov-uk-colours-and-font/), which we're activating here but maintaining the legacy base font size for now. We will address the new base font size in a future PR.
> Switch colours to new higher contrast

- app/controllers/calendar_controller.rb
- app/presenters/faq_presenter.rb
- app/views/calendar/_calendar_footer.html.erb
- app/views/calendar/bank_holidays.html.erb
- app/views/calendar/when_do_the_clocks_change.html.erb
- test/unit/presenters/faq_presenter_test.rb
This one doesn't get a rich result because there's only one question.
---
[Trello card](https://trello.com/c/4jEs6raZ/1155-faq-scheme-for-uk-bank-holiday-page)
> Add FAQ metadata to pages

- app/models/calendar.rb
- test/integration/bank_holidays_test.rb
2nd December 2019 is a substitute bank holiday in Scotland for St Andrew's Day. The [current implementation of `Calendar#bunting_styles`](https://github.com/alphagov/calendars/blob/48a6ed35cf2784651441a9024b93a932b4e5f2c1/app/models/calendar.rb#L49-L55) uses tinsel for all bank holidays with `"bunting": true` in December and January, but it should probably only do that for the ones for Christmas and New Year:
There were substitute days for St Andrew's Day in 2013 and 2014 as well. I've used one of those in the test because for some reason the test isn't failing today when I use the 2019 date - maybe something to do with Timecop?
> Add a failing test for tinsel not being used in early December

- app/views/layouts/application.html.erb
Small change to the SRI of the JavaScript to use `crossorigin='use-credentials'` rather than `crossorigin='anonymous'`. This change is part of [RFC-114](https://github.com/alphagov/govuk-rfcs/pull/114).
> Change crossorigin from 'anonymous' to 'use-credentials'

- app/views/layouts/application.html.erb
Reverts alphagov/calendars#757
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://assets.integration.publishing.service.gov.uk/frontend/frontend-7f9a59db277ec340f1dc70fbf02c886072883f9243a91384b2c6405ecf3be4a9.js’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).`
Need to investigate this issue first.
> Revert "Change crossorigin from 'anonymous' to 'use-credentials'"

- lib/ics_renderer.rb
- test/unit/ics_renderer_test.rb
We used to use indices to generate UIDs. This meant that when we deleted
some past bank holidays back in December 2019, the indices pointed to
different events.
Using a combination of event title and event date instead of indices to
create event UIDs means that these will remain unique even when we'll
delete other past bank holidays in the future.
We can use event title and event date to make the UIDs uniques because
there are never going to be two bank holidays with the same name on the
same day.
More info and background can be found here:
- [Commit that deleted old bank holidays](https://github.com/alphagov/calendars/commit/c28e7b570c39a10f60d2ed13b85d477b9a60159e#diff-1569053def8d48383b565a3d2d505529)
- [Issue raised by a member of the …
> Make the event UIDs for the ical files unique

- lib/ics_renderer.rb
- test/unit/ics_renderer_test.rb
Hey,
Thanks again for your work on the bank holiday calendar UID update.
This is a simple piece of defensive programming after observing this UID in the latest production .ics output:
```
BEGIN:VEVENT
DTEND;VALUE=DATE:20150102
DTSTART;VALUE=DATE:20150101
SUMMARY:New Year’s Day
UID:ca6af7456b0088abad9a69f9f620f5ac-2015-01-01-NewYear’sDay@gov.uk
SEQUENCE:0
DTSTAMP:20200210T141037Z
END:VEVENT
```
After my proposed change the UID line will come out as:
```
UID:ca6af7456b0088abad9a69f9f620f5ac-2015-01-01-NewYearsDay@gov.uk
```
Removing non-word characters seemed like the best way to avoid accounting for the text [escaping rules](https://tools.ietf.org/html/rfc5545#section-3.3.11) in the ICS format spec. Without this change, an event name with a `:` or `;` or `,` in could break an otherwise …
> Remove non-word characters from event UIDs

- lib/data/bank-holidays.json
Given the COVID-19 pandemic and people being asked to stay at home, it would be inappropriate to decorate GOV.UK with bunting at this time.
> Remove bunting for 2020 Easter Monday

- lib/data/bank-holidays.json
In 5606d77, bunting was only removed for Northern Ireland.  This also removes the bunting for England & Wales.
Easter Monday is not a bank holiday in Scotland.
> Remove 13/04/2020 bunting for England and Wales

- app/assets/stylesheets/application.scss
- buttons aren't used in the application, but they do appear in the cookie banner, and are presently unstyled
- we might need a better fix for this as buttons don't appear in the suggested sass for this application, so there is a risk they could be removed accidentally, but I've added a comment to reduce that risk
- don't need the print styles for buttons, because the cookie banner is not shown in print
Fixes this:
> Add button sass to calendars
